### ISSUE TITLE
请问您的BIOS是如何设置的？

### ISSUE THREAD

**Issue by possibleit** [choecode/B460M-MORTAR-i5-10400-OC0.7.5-Monterey-12.1beta-UEFI#2]
你好，我用的和你一样的配置，10400，微星B460M迫击炮，RX6600，安装开始时屏幕上就显示禁止符号，请问您的BIOS是如何设置的？

**Comment by choecode** [comment]
只开一个DTM就可以了。
这一个开了的话，其余的会自动设置的。

**Comment by choecode** [comment]
> 你好，我用的和你一样的配置，10400，微星B460M迫击炮，RX6600，安装开始时屏幕上就显示禁止符号，请问您的BIOS是如何设置的？

对了，我建议你可以先用核显把黑苹果安装和调试好。最后再弄独显的事情。

**Comment by possibleit** [comment]
多谢，查了错误的跑码发现是usb的问题，开启了advisefeature更换启动盘到usb2.0之后，成功安装了系统。但是进入系统之后无线网卡可正常驱动wifi，却不能驱动蓝牙。请问您的EFI文件中是否定制了USB驱动，蓝牙接的是哪个USB2口？我的无线网卡是使用PCIE转接卡转接，蓝牙转接线连接到主板的9针端子上。

**Comment by choecode** [comment]
网卡型号有没有> 多谢，查了错误的跑码发现是usb的问题，开启了advisefeature更换启动盘到usb2.0之后，成功安装了系统。但是进入系统之后无线网卡可正常驱动wifi，却不能驱动蓝牙。请问您的EFI文件中是否定制了USB驱动，蓝牙接的是哪个USB2口？我的无线网卡是使用PCIE转接卡转接，蓝牙转接线连接到主板的9针端子上。

**Comment by choecode** [comment]
没有定制usb哦，usb3.0和typec不能用，但我觉得无所谓> 多谢，查了错误的跑码发现是usb的问题，开启了advisefeature更换启动盘到usb2.0之后，成功安装了系统。但是进入系统之后无线网卡可正常驱动wifi，却不能驱动蓝牙。请问您的EFI文件中是否定制了USB驱动，蓝牙接的是哪个USB2口？我的无线网卡是使用PCIE转接卡转接，蓝牙转接线连接到主板的9针端子上。

**Comment by possibleit** [comment]
网卡型号是DW1820A

**Comment by choecode** [comment]
> 网卡型号是DW1820A

我搜了下资料，这个网卡是需要单独配置驱动的，我直接买的免驱卡，所以就没有关注过这一块。。

**Comment by possibleit** [comment]
好的，多谢，我再搞搞驱动。之前在笔记本上1820是免驱的，看来在桌面端还需要配驱动。
