### ISSUE TITLE
请问只有核显怎么修改？

### ISSUE THREAD

**Issue by yzxcool123** [choecode/B460M-MORTAR-i5-10400-OC0.7.5-Monterey-12.1beta-UEFI#3]

**Comment by choecode** [comment]
DeviceProperties改成下面的试试

```
<key>DeviceProperties</key>
<dict>
  <key>Add</key>
  <dict>
	  <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
	  <dict>
		  <key>AAPL,ig-platform-id</key>
		  <data>AACbPg==</data>
	  </dict>
        </dict>
</dict>```

**Comment by choecode** [comment]
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>AACbPg==</data>
			</dict>
		</dict>
	</dict>

**Comment by choecode** [comment]
定义了AAPL,ig-platform-id的这个值，可以理解为 核显提供输出。好像有2个可选值，你先用这个，理论上都可以启动。只是设置缓冲帧什么的需要调整，我办公机器用的就是这个。但是设置了缓冲帧相关的内存大小就会黑屏。主板是华硕的，所以还是要根据实际情况来慢慢调整。

**Comment by yzxcool123** [comment]
好的，我试一下，非常感谢！

**Comment by choecode** [comment]
> 好的，我试一下，非常感谢！

不行的话加微信探讨下也可以。wxwxgdyw_ylsh
